Backend setup
PurpJell/MoviEh pull request #3
Opened 2024-10-18 09:25 UTC by PurpJell

2024-10-18 09:43 UTC, rimvydascivilis commented
Can we change `/movieh` to `/backend` for consistency, since we have `/frontend`?

2024-10-18 09:44 UTC, rimvydascivilis requested changes

2024-10-18 09:44 UTC, rimvydascivilis commented on .gitignore
Can we move this file to `/movieh`?

2024-10-18 09:44 UTC, rimvydascivilis commented on movieh/db.sqlite3
Is this a necessary file if we're going to use PostgreSQL?

2024-10-18 09:44 UTC, rimvydascivilis commented on movieh/movieh/settings.py
> +SECRET_KEY = 'django-insecure-vd6t$%08dvi5yhhzhxlq_!06ta9a5ecx-m%owpkym%x(6rcc=s'
Can we get secrets from env variables?

2024-10-18 09:44 UTC, rimvydascivilis commented on movieh/movieh/settings.py
> +        'ENGINE': 'django.db.backends.postgresql',
Also get db config from env vars

2024-10-18 09:44 UTC, rimvydascivilis commented on movieh/movieh/urls.py
> +class UserSerializer(serializers.HyperlinkedModelSerializer):
`UserSerializer` class should be in `serializers.py` file

2024-10-18 09:44 UTC, rimvydascivilis commented on movieh/movieh/urls.py
> +class UserViewSet(viewsets.ModelViewSet):
This class should be in `views.py` file

2024-10-18 09:53 UTC, rimvydascivilis commented
Could you add `requirements.txt` dependency file?

2024-10-18 11:08 UTC, rimvydascivilis requested changes

2024-10-18 11:08 UTC, rimvydascivilis commented on backend/movieh/urls.py
> +# from ..moviehApp.views import UserViewSet
remove this

2024-10-18 11:08 UTC, rimvydascivilis commented on backend/movieh/settings.py
Use https://pypi.org/project/dj-database-url/ for database connection configuration
```suggestion
import dj_database_url
```

2024-10-18 11:08 UTC, rimvydascivilis commented on backend/movieh/settings.py
Also install that package and add to `requirements.txt`

2024-10-18 11:08 UTC, rimvydascivilis commented on backend/movieh/settings.py
Its better to have one variable which sets the db connection.
```py
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'postgres://user:p%23ssword!@localhost/foobar'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}
```

2024-10-18 13:37 UTC, rimvydascivilis requested changes

2024-10-18 13:37 UTC, rimvydascivilis commented on backend/movieh/settings.py
> +        default=os.getenv('DB_CONNECTION', 'postgres://username:password@localhost:port/database'),
Default url should be valid. Update default url so it connects to local dev db.

2024-10-18 19:45 UTC, PurpJell commented on backend/movieh/settings.py
> +        default=os.getenv('DB_CONNECTION', 'postgres://username:password@localhost:port/database'),
Just to make sure, is this local dev database the one, that i have set up manually or is there another?

2024-10-19 16:37 UTC, rimvydascivilis commented on backend/movieh/settings.py
> +        default=os.getenv('DB_CONNECTION', 'postgres://username:password@localhost:port/database'),
We can agree to use the following Docker configuration. Update the database URL to `postgresql://user:password@localhost:5432/movieh` and modify `/docker-compose.yml` as follows:
```dockerfile
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT=80
    networks:
      - app-network
    ports:
      - "80:80"

  database:
    image: postgres:17-alpine
    networks:
      - app-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movieh
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  db-data:
  ```

2024-10-20 11:30 UTC, rimvydascivilis approved these changes
LTGM

2024-10-20 11:31 UTC, merged